#!/bin/bash
SETUP_DIR="/mnt/setup"
TMP_INSTALL="${SETUP_DIR}/tmp"
DIRLOG="${SETUP_DIR}/log"
DIR_SYSTEM="/mnt/yaxkin"
CHROOT_YAXKIN="chroot /mnt/yaxkin"
TMP="/mnt/setup/tmp"



dialog --title ' Ajuste o relógio do sistema ' --timebox '\nDICA: Use as setas e o TAB.'   0 0 2> $TMP/SeTdate
cat $TMP/SeTdate |sed s,\:`cut -d: -f3 $TMP/SeTdate`,,g |sed s,\:,,g > $TMP/hora
# rm -f $TMP/hora

if [ -r $TMP/hora ]; then
date -s $( cat $TMP/hora )  1> /dev/null 2> /dev/null
hwclock -w  1> /dev/null 2> /dev/null
fi
rm -f $TMP/hora
