#!/bin/bash

TMP=/mnt/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
rm -f $TMP/selectconf
dialog --backtitle "Yaxkin Configuration Tools" \
--title " SELECIONE A OPÇÃO DESEJADA " --menu \
"Por favor escolha uma opção abaixo para prosseguir com a configuração:\n" \
10 80 6 \
"NETWORK" "Configure a rede do Yaxkin" \
"HOSTNAME" "Configure o hostname do Yaxkin" \
2> $TMP/selectconf
if [ ! $? = 0 ]; then
 rm $TMP/selectconf
 exit
fi

SELECT_CONFIGURE="`cat $TMP/selectconf`"
rm -f $TMP/selectconf
if [ "${SELECT_CONFIGURE}" = "NETWORK" ]; then
SeTnetwork
elif [ "${SELECT_CONFIGURE}" = "HOSTNAME" ]; then
 SeThostname
fi
