#!/bin/bash

SETUP_DIR="/mnt/setup"
TMP_INSTALL="${SETUP_DIR}/tmp"
DIRLOG="${SETUP_DIR}/log"
DIR_SYSTEM="/mnt/yaxkin"
CHROOT_YAXKIN="chroot /mnt/yaxkin"
TMP="/mnt/setup/tmp"

# limpando arquivos de configuração
rm -f $TMP/selectNET

# criando lista de interfaces disponiveis
ifconfig -a |cut -d" " -f1|grep eth > $TMP/SeTinterfaces
ifconfig -a |cut -d" " -f1|grep wlan >> $TMP/SeTinterfaces
ARQUIVO="$TMP/SeTinterfaces"

dialog --backtitle "Yaxkin Network Tools" \
 --title " SELECIONE UM DISPOSITIVO DE REDE " \
  --menu 'Selecione o dispositivo principal para ser configurado:' \
 10 35 6 $(cat $ARQUIVO | cut -d: -f1 | sed s,$," # ",) 2> $TMP/selectNET

  if [ ! $? = 0 ]; then
   rm $TMP/selectNET
    exit
    fi

DEVICE=$( cat $TMP/selectNET )

if [ -r $TMP/selectNET ]; then
rm -rf ${TMP_INSTALL}/net
fi

dialog --backtitle "Yaxkin Network Tools" --title " SELECIONE O TIPO DE CONFIGURAÇÃO " \
--menu "Selecione o tipo de configuração permanente para o dispositivo ${DEVICE}:\n\n" 11 48 12 \
"DHCP" "Configure um ip dinâmico." \
"FIXO" "Configure um ip fixo." 2> $TMP/selectNETtype

  if [ ! $? = 0 ]; then
   rm $TMP/selectNETtype
    exit
    fi

NETSELECT=$( cat $TMP/selectNETtype )
#################################

if [ "$NETSELECT" = "DHCP" ]; then
cp ${SETUP_DIR}/templates/etc/conf.d/net.dhcp.template ${TMP_INSTALL}/net
sed -i s,'{IFACE}',${DEVICE},g ${TMP_INSTALL}/net
fi

#################################

# configurando IP estático

if [ "$NETSELECT" = "FIXO" ]; then
lerIP=""

while [ -z "$lerIP" ]; do
# configurando IP
lerIP=$( dialog --stdout --title ' Yaxkin Network Setup ' --inputbox "Digite o ip da interface ${DEVICE}:\n\n" 8 40 )

        if [ -z "$lerIP" ]; then
	dialog --title " Erro ao configurar interface de rede " --msgbox "\nDigite um ip válido.\n" 7 50
        fi
done

#################################

# configurando NETMASK
lerNETMASK=""

while [ -z "$lerNETMASK" ]; do
# configurando NETMASK
lerNETMASK=$( dialog --stdout --title ' Yaxkin Network Setup ' --inputbox "Digite a mascara da rede: (ex: 255.255.255.0):\n\n" 8 40 )
        if [ -z "$lerNETMASK" ]; then
	dialog --title " Erro ao configurar interface de rede " --msgbox "\nDigite um NETMASK válido.\n" 7 50
        fi
done

#################################

# configurando BROADCAST
lerBRD=""

while [ -z "$lerBRD" ]; do
# configurando BRD
lerBRD=$( dialog --stdout --title ' Yaxkin Network Setup ' --inputbox "Digite o broadcast da rede: (ex: 192.168.0.255):\n\n" 8 40 )
        if [ -z "$lerBRD" ]; then
	dialog --title " Erro ao configurar interface de rede " --msgbox "\nDigite um BROADCAST válido.\n" 7 50
        fi
done

#################################

# configurando ROUTER
lerROUTER=""

while [ -z "$lerROUTER" ]; do
# configurando ROUTER
lerROUTER=$( dialog --stdout --title ' Yaxkin Network Setup ' --inputbox "Digite o ip do roteador:\n\n" 8 40 )
        if [ -z "$lerROUTER" ]; then
	dialog --title " Erro ao configurar interface de rede " --msgbox "\nDigite um ip de Gateway válido.\n" 7 50
        fi
done

#################################

# configurando DNS1
lerDNS1=""

while [ -z "$lerDNS1" ]; do
# configurando DNS
lerDNS1=$( dialog --stdout --title ' Yaxkin Network Setup ' --inputbox "Digite o ip do servidor DNS primario:\n\n" 8 40 )
        if [ -z "$lerDNS1" ]; then
	dialog --title " Erro ao configurar interface de rede " --msgbox "\nDigite um ip válido para o DNS primário.\n" 7 50
        fi
done

# configurando DNS2
lerDNS2=$( dialog --stdout --title ' Yaxkin Network Setup ' --inputbox "Digite o ip do servidor DNS secundario (opcional):\n\n" 8 40 )

#################################
cp ${SETUP_DIR}/templates/etc/conf.d/net.template ${TMP_INSTALL}/net

sed -i s,'{IP}',${lerIP},g ${TMP_INSTALL}/net
sed -i s,'{NETMASK}',${lerNETMASK},g ${TMP_INSTALL}/net
sed -i s,'{BRD}',${lerBRD},g ${TMP_INSTALL}/net
sed -i s,'{ROUTER}',${lerROUTER},g ${TMP_INSTALL}/net
sed -i s,'{DNS}',"${lerDNS1} ${lerDNS2}",g ${TMP_INSTALL}/net
sed -i s,'{IFACE}',${DEVICE},g ${TMP_INSTALL}/net

# definindo servidor DNS
echo "nameserver ${lerDNS1} ${lerDNS2}" > ${DIR_SYSTEM}/etc/resolv.conf
fi

#################################
# copiando arquivo de conf net para o diretorio do yaxkin
cp ${TMP_INSTALL}/net ${DIR_SYSTEM}/etc/conf.d/net

# ativando ${DEVICE} no boot
${CHROOT_YAXKIN} ln -s /etc/init.d/net.lo /etc/init.d/net.${DEVICE}
${CHROOT_YAXKIN} rc-update add net.${DEVICE} default
