#!/bin/bash
PATH="$PATH:/mnt/setup"
export PATH;

SETUP_DIR="/mnt/setup"
TMP_INSTALL="${SETUP_DIR}/tmp"
LIVECD_ROOT_FS="/mnt/livecd/yaxkin"

SELECIONADO=`cat ${TMP_INSTALL}/SeTversion`
VERSAO_ATUAL=`ls ${LIVECD_ROOT_FS}/${SELECIONADO}/*amd64-*bz2|cut -d'-' -f4|sed s,'.tar.bz2',,g`

NOME_SELECIONADO=`echo ${SELECIONADO} |sed s,server,Server,g |sed s,desktop,Desktop,g`
YAXKIN_VERSION="Yaxkin Linux ${NOME_SELECIONADO} ${VERSAO_ATUAL}"

DIR_SYSTEM="/mnt/yaxkin"
CHROOT_YAXKIN="chroot /mnt/yaxkin"
MSG_PAUSE="Pressione uma tecla para continuar..."
ERROR="0"
DATA=`date +%d-%m-%Y`

DIRLOG="${SETUP_DIR}/log"
ERRORLOG="${DIRLOG}/error.log"

if [ ! -d ${DIRLOG} ];then
        mkdir -p ${DIRLOG}
	fi

#unpack system
( pv -n ${LIVECD_ROOT_FS}/${SELECIONADO}/*amd64-${SELECIONADO}-${VERSAO_ATUAL}.tar.bz2 | tar xjf - -C ${DIR_SYSTEM} ) 2>&1 | dialog --gauge "Descompactando stage4 do Yaxkin Linux em ${DIR_SYSTEM}..." 8 70 0 2> ${ERRORLOG}

#criar devs
# Criando dispositivos de sistema.

mknod -m 660 ${DIR_SYSTEM}/dev/console c 5 1 > /dev/null 2> /dev/null
mknod -m 600 ${DIR_SYSTEM}/dev/initctl p > /dev/null 2> /dev/null
mknod -m 660 ${DIR_SYSTEM}/dev/tty1 c 4 1 > /dev/null 2> /dev/null
mknod -m 660 ${DIR_SYSTEM}/dev/null c 1 3 > /dev/null 2> /dev/null

#unpack portage
( pv -n ${LIVECD_ROOT_FS}/portage-latest.tar.bz2 | tar xjf - -C ${DIR_SYSTEM}/usr ) 2>&1 | dialog --gauge "Descompactando Portage oficial em ${DIR_SYSTEM}/usr..." 8 70 0 2> ${ERRORLOG}


# Montando ambiente chroot
mount -t proc none ${DIR_SYSTEM}/proc 2> ${ERRORLOG}
mount -o bind /dev ${DIR_SYSTEM}/dev 2> ${ERRORLOG}
mount -o bind /sys ${DIR_SYSTEM}/sys 2> ${ERRORLOG}

#sistema
# Criando fstab...
dialog --title " Yaxkin Linux " --backtitle "Criando arquivos de configuração do Yaxkin Linux" --infobox "\nCriando /etc/fstab..." 5 50 && sleep 1
cat ${TMP_INSTALL}/SeTnative > ${DIR_SYSTEM}/etc/fstab
cat ${TMP_INSTALL}/SeTswap >> ${DIR_SYSTEM}/etc/fstab
cat ${SETUP_DIR}/templates/etc/fstab.template >> ${DIR_SYSTEM}/etc/fstab
cp ${DIR_SYSTEM}/etc/fstab ${TMP_INSTALL}/fstab

#########################################

## rede ##

 dialog --title " Yaxkin Linux " --msgbox "\n Configure o hostname,\n\
 Pressione [ENTER] para continuar..." 8 42

# configura hostname
SeThostname

# configura ethernet principal
dialog --title " Yaxkin Linux " --msgbox "\nConfigure a interface de rede\n" 7 50
SeTnetwork

#########################################
# copiando make.conf

dialog --title " Yaxkin Linux " --backtitle "Criando arquivos de configuração do Yaxkin Linux" --infobox "\nCriando /etc/make.conf..." 5 50 && sleep 1
cp  ${LIVECD_ROOT_FS}/${SELECIONADO}/make.conf ${DIR_SYSTEM}/etc/portage

#########################################
# definindo fuso-horário
 dialog --title " Yaxkin Linux " --msgbox "\n Configure o fuso horário,\n\
 Pressione [ENTER] para continuar..." 8 42

dialog --title " Yaxkin Linux " --backtitle "Criando arquivos de configuração do Yaxkin Linux" --infobox "\nDefinindo fuso horário para America/Sao_Paulo..." 5 60 && sleep 1
cp ${DIR_SYSTEM}/usr/share/zoneinfo/America/Sao_Paulo ${DIR_SYSTEM}/etc/localtime
echo "America/Sao_Paulo" > ${DIR_SYSTEM}/etc/timezone
${CHROOT_YAXKIN} hwclock --systohc

#########################################
# criando lista de locales

dialog --title " Yaxkin Linux " --backtitle "Criando arquivos de configuração do Yaxkin Linux" --infobox "\nGerando lista de locales do sistema..." 5 60 && sleep 1
echo "en_US.UTF-8 UTF-8" > ${DIR_SYSTEM}/etc/locale.gen
echo "en_US ISO-8859-1" >> ${DIR_SYSTEM}/etc/locale.gen
echo "pt_BR.UTF-8 UTF-8" >> ${DIR_SYSTEM}/etc/locale.gen
echo "pt_BR ISO-8859-1" >> ${DIR_SYSTEM}/etc/locale.gen

# gerando locales
${CHROOT_YAXKIN} locale-gen

# definindo idioma padrão
dialog --title " Yaxkin Linux " --backtitle "Criando arquivos de configuração do Yaxkin Linux" --infobox "\nDefinindo LANG e LC_ALL para pt_BR.UTF-8..." 5 60 && sleep 1
echo "export LC_ALL=pt_BR.UTF-8" >> ${DIR_SYSTEM}/etc/profile
echo "export LANG=pt_BR.UTF-8" >> ${DIR_SYSTEM}/etc/profile

#########################################
# definindo mapa de teclado

KEYMAP_YAXKIN=`cat ${TMP_INSTALL}/Pkeymap`

dialog --title " Yaxkin Linux " --backtitle "Criando arquivos de configuração do Yaxkin Linux" --infobox "\nDefinindo mapa de teclado para ${KEYMAP_YAXKIN}..." 5 60 && sleep 1
cp ${SETUP_DIR}/templates/etc/conf.d/keymaps.template ${TMP_INSTALL}/keymaps
sed -i s,{KEYMAP},${KEYMAP_YAXKIN},g ${TMP_INSTALL}/keymaps
cp ${TMP_INSTALL}/keymaps ${DIR_SYSTEM}/etc/conf.d/keymaps

#########################################
# configurando log do rc.conf

dialog --title " Yaxkin Linux " --backtitle "Criando arquivos de configuração do Yaxkin Linux" --infobox "\nAtivando logs do OpenRC..." 5 60 && sleep 1
sed -i s,'#rc_logger="YES"','rc_logger="YES"',g ${DIR_SYSTEM}/etc/rc.conf
sed -i s,'#rc_sys="YES"','rc_sys="YES"',g ${DIR_SYSTEM}/etc/rc.conf

#########################################
# configurando grub

SeTgrub

#########################################
# Definindo /etc/motd
cat ${SETUP_DIR}/yaxkin_logo_ascii.txt > ${DIR_SYSTEM}/etc/motd
echo -e "\n\n${YAXKIN_VERSION} - Have a lot of fun...\n" >> ${DIR_SYSTEM}/etc/motd
echo -e "${YAXKIN_VERSION}" > ${DIR_SYSTEM}/etc/issue.yaxkin


#########################################
# definindo senha de root
#echo -e "Defina a senha de root"
#${CHROOT_YAXKIN} passwd root
SeTpasswd

