#!/bin/bash
DIR_SYSTEM="/mnt/yaxkin"
DIR_SETUP="/mnt/setup"
TMP="${DIR_SETUP}/tmp"
cd /
umount ${DIR_SYSTEM}/sys ${DIR_SYSTEM}/dev ${DIR_SYSTEM}/proc ${DIR_SYSTEM} > /dev/null 2> /dev/null

# gera lista de partições montadas
mount|grep yaxkin|cut -d" " -f1 |grep -v "$( mount|grep 'on /mnt/yaxkin type' |cut -d" " -f1 )" > /tmp/list-mount 2> /dev/null

while read device;do
umount -f ${device} > /dev/null 2> /dev/null
done < /tmp/list-mount
sleep 1
umount -f ${DIR_SYSTEM} > /dev/null 2> /dev/null
