#!/bin/sh

#################################################################################
# Area31 Hackerspace
#
# BSD License - do whatever you want with this script
#
# As always, bug reports, suggestions, etc: raphaelbastos@hackstore.com.br
#################################################################################

export HISTTIMEFORMAT="%h/%d - %H:%M:%S - "

DIR_MNT="/mnt/custom"
TMP="/tmp/sysresccd-area31"

if [ ! -d ${TMP} ]; then
	mkdir -p ${TMP}
fi

# clear tmpdir
rm -f ${TMP}/SeT*
rm -f ${TMP}/hdset

# If a keyboard map has been previously configured, it restores the data
if [ -r ${TMP}/Pkeymap ]; then
	cp ${TMP}/Pkeymap ${TMP}/SeTkeymap
fi

# turn on color menus
echo "on" > ${TMP}/SeTcolor
export COLOR=on

# Activate all LVM VGs
vgchange -ay 1> /dev/null 2> /dev/null

# Check if Linux partitions exist
if fdisk -l 2> /dev/null | egrep -i 'Linux$' 1> /dev/null 2> /dev/null ; then
	fdisk -l 2> /dev/null | egrep -i 'Linux$' | sort 1> $TMP/SeTplist 2> /dev/null
else
	dialog --title " NENHUMA PARTIÇÃO LINUX DETECTADA " \
	--msgbox "\n Parece que não existe nenhuma partição Linux nesta máquina.\
	\n\n Você precisará criar pelo menos uma para o RescueCD Area31 Tools\n\
	 Para fazer isso, você precisa escolher a opção 'PARTITION-EDITOR' no\n\
	 menu principal, e criar as partições usando o 'cfdisk' ou 'fdisk'\n\n\
	 Para mais informações, leia a HELP no menu a seguir.\n\n\
	 Lembre-se também de criar uma partição SWAP de pelo menos 2GB" 15 71
fi

################################################################
# menu

while [ 0 ]; do
	dialog --title " RescueCD Area31 Tools " --item-help --menu "Bem vindo ao RescueCD Area31 Tools!\n\n\
	Selecione uma opção usando as teclas direcionais UP/DOWN e pressione [SPACE] ou [ENTER].\n\
	Teclas alternativas também podem ser usadas: '+', '-' e [TAB]." 0 0 0 \
	"HELP" "Obtenha ajuda para uso do RescueCD Area31 Tools" "Obtenha ajuda para uso do RescueCD Area31 Tools" \
	"SHOW" "Exibe os discos e swap ativas" "Exibe os discos e swap ativas" \
	"KEYMAP" "Configure keymap" "Default: \"us\"" \
	"PARTITION-EDITOR" "Particionador de disco" "CUIDADO: Essas ferramentas podem causar danos irreversíveis em seu disco!"  \
	"FORMAT" "Formata a partição \"/mnt/custom\"" "LEMBRE-SE: Antes de formatar particione o disco" \
	"ADD-SWAP" "Configure e monte a SWAP" "LEMBRE-SE: Antes de montar a swap particione e crie uma partição do tipo \"82 (swap)\"" \
	"ADD-TARGET" "Configure a partição \"/mnt/custom\"" "LEMBRE-SE: Antes de montar \"/mnt/custom\" particione e formate a partição" \
	"EXTRACT" "Extraia os arquivos da imagem \"sysrcd.dat\" para o diretório \"/mnt/custom\"" "LEMBRE-SE: Antes de extrair a imagem acesse a opção \"ADD-TARGET\" para montar o \"/mnt/custom\"" \
	"CHROOT" "Personalize  o RescueCD via chroot" "LEMBRE-SE: Antes de montar o chroot acesse a opção \"ADD-TARGET\" para montar o \"/mnt/custom\"" \
	"GEN-ISO" "Gere uma nova imagem ISO personalizada" "Antes de gerar uma ISO acesse a opção \"ADD-TARGET\" para montar o \"/mnt/custom\""  \
	"DATE-TIME" "Defina a hora do sistema" "Timezone atual: $(date +'%:z %Z')" \
	"UMOUNT" "Desmonta todos os discos montados incluso swap." "Recomendável antes de reboot ou halt" \
	"EXIT" "Sair do do RescueCD Area31 Tools" "ATENÇÃO: É recomendado que se desmonte todos os discos incluso swap antes de sair, bastando acessar a opção \"UMOUNT\"."  2> $TMP/hdset
	if [ ! $? = 0 ]; then
		exit
	fi
	MAINSELECT="`cat $TMP/hdset`"
	#rm $TMP/hdset

	################################################################
	# HELP

	if [ "${MAINSELECT}" = "HELP" ]; then
		sh /usr/share/sysresccd-area31/sysresccd-area31-help
	fi

	################################################################
	# SHOW

	if [ "${MAINSELECT}" = "SHOW" ]; then
		sh /usr/share/sysresccd-area31/sysresccd-area31-showmount
	fi

	################################################################
	# PARTITION-EDITOR

	if [ "${MAINSELECT}" = "PARTITION-EDITOR" ]; then
		dialog --title " BEM VINDO AO PARTITION-EDITOR " --msgbox "\n\
		O RescueCD Area31 precisa de algumas coisas:\n\n\
		1. Crie pelo menos uma partição Linux.\n\
		2. If possible, create a SWAP partition (recommended).\n\n\
		Press [ENTER] to continue" 12 60
		sh /usr/share/sysresccd-area31/sysresccd-area31-partition
	fi

	################################################################
	# FORMAT

	if [ "${MAINSELECT}" = "FORMAT" ]; then
		dialog --title " RescueCD Area31 Tools " --msgbox "\n Format partition (required to chroot),\n\
		Press [ENTER] to continue..." 8 55
		sh /usr/share/sysresccd-area31/sysresccd-area31-format
	fi

	#################################################################
	# MAPA DE TECLADO

	if [ "${MAINSELECT}" = "KEYMAP" ]; then
		dialog --title " RescueCD Area31 Tools " --msgbox "\n Configure keymap,\n\
		Press [ENTER] to continue..." 8 42
		sh /usr/share/sysresccd-area31/sysresccd-area31-keymap
	fi

	################################################################

	# SWAP

	if [ "${MAINSELECT}" = "ADD-SWAP" ]; then
		dialog --title " RescueCD Area31 Tools " --msgbox "\n Configure SWAP,\n\
		Press [ENTER] to continue..." 8 42
		sh /usr/share/sysresccd-area31/sysresccd-area31-swap
	fi

	################################################################
	# ADD-TARGET

	if [ "${MAINSELECT}" = "ADD-TARGET" ]; then
		dialog --title " RescueCD Area31 Tools " --msgbox "\n Monte o disco para o ambiente chroot,\n\
		Press [ENTER] to continue..." 8 55
		sh /usr/share/sysresccd-area31/sysresccd-area31-targets mount-disk
	fi

	#################################################################
	# EXTRACT

	if [ "${MAINSELECT}" = "EXTRACT" ]; then
		var=0
		var="$(mount | grep -w "${DIR_MNT}" | wc -l)"

		if [ "$var" -ne 0 ];then
			dialog --title " RescueCD Area31 Tools " --no-label Cancel --yes-label Continue --yesno \
			"\nExtract sysrcd.dat to /mnt/custom,\nPress [ENTER] to continue..." 8 65
			if [ "$?" -eq 0 ]; then
				/usr/sbin/sysresccd-custom extract
			fi
		else
			dialog --title " ERRO AO CONFIGURAR RESCUECD " --msgbox "\n\
			O RescueCD Area31 Tools precisa de uma partição "/mnt/custom" montada:\n\n\
			1. Selecione pelo menos uma partição para extrair a imagem sysrcd.dat\n\
			do RescueCD usando a opção "ADD-TARGET" no menu principal\n\n\
			2. If possible, create a SWAP partition (recommended)\n
			\n
			if necessary, configure keymap\n\n
			Press [ENTER] return to main menu" 16 76
			continue
		fi
	fi

	#################################################################
	# CHROOT

	if [ "${MAINSELECT}" = "CHROOT" ]; then
		var=0
		var="$(mount | grep -w "${DIR_MNT}" | wc -l)"

		if [ "$var" -ne 0 ];then
			dialog --title " RescueCD Area31 Tools " --no-label Cancel --yes-label Continue --yesno \
			"\nFaça CHROOT em \"/mnt/custom\",\nPress [ENTER] to continue..." 8 55
			if [ "$?" -eq 0 ]; then
				sh /usr/share/sysresccd-area31/sysresccd-area31-targets make-chroot
			fi
		else
			dialog --title " ERRO AO CONFIGURAR RESCUECD " --msgbox "\n\
			O RescueCD Area31 Tools precisa de uma partição "/mnt/custom" montada:\n\n\
			1. Selecione pelo menos uma partição para o ambiente chroot\n\
			do RescueCD usando a opção "ADD-TARGET" no menu principal\n\n\
			2. If possible, create a SWAP partition (recommended)\n
			\n
			if necessary, configure keymap\n\n
			Press [ENTER] return to main menu" 16 76
			continue
		fi
	fi

	#################################################################
	# configura hora do RescueCD Area31

	if [ "${MAINSELECT}" = "DATE-TIME" ]; then
		sh /usr/share/sysresccd-area31/sysresccd-area31-fixdate
	fi

	########################################################3
	# GEN-ISO

	if [ "${MAINSELECT}" = "GEN-ISO" ]; then
		var=0
		var="$(mount | grep -w "${DIR_MNT}" | wc -l)"

		if [ "$var" -ne 0 ];then
			dialog --title " RescueCD Area31 Tools " --no-label Cancel --yes-label Continue --yesno \
			"\nMake new ISO on /mnt/custom/customcd/isofile,\nPress [ENTER] to continue..." 8 55
			if [ "$?" -eq 0 ]; then
				sh /usr/share/sysresccd-area31/sysresccd-area31-targets make-iso
			fi
		else
			dialog --title " ERRO AO CONFIGURAR RESCUECD " --msgbox "\n\
			O RescueCD Area31 Tools precisa de uma partição montada em "/mnt/custom".\n\n\
			1. Selecione pelo menos uma partição para gerar a ISO\n\
			do RescueCD usando a opção "ADD-TARGET" no menu principal\n\n\
			2. If possible, create a SWAP partition (recommended)\n
			\n
			if necessary, configure keymap\n\n
			Press [ENTER] return to main menu" 16 76
			continue
		fi
	fi

	#######################################################
	# configura hora do RescueCD Area31

	if [ "${MAINSELECT}" = "DATE-TIME" ]; then
		sh /usr/share/sysresccd-area31/sysresccd-area31-fixdate
	fi

	#######################################################
	# Umount all partitions

	if [ "${MAINSELECT}" = "UMOUNT" ]; then
		dialog --title " RescueCD Area31 Tools " --msgbox "\n Umount all partitions, include /mnt/custom!,\n\
		Press [ENTER] to continue..." 8 62
		sh /usr/share/sysresccd-area31/sysresccd-area31-showmount
		sh /usr/share/sysresccd-area31/sysresccd-area31-targets umount-disk
		sh /usr/share/sysresccd-area31/sysresccd-area31-showmount
	fi

	if [ "${MAINSELECT}" = "EXIT" ]; then
		RESCUECD_MOUNTED=$( mount |grep -w /mnt/custom|wc -l  )

		sh /usr/share/sysresccd-area31/sysresccd-area31-targets umount-chroot
		# umount all partitions
		if [ "${RESCUECD_MOUNTED}" -ne 0 ];then
			break
		else
			break
		fi
	fi
done # end of menu
#######################################################################
# end script
