#!/bin/bash

DIR_MNT="/mnt/custom"
DIR_SYSTEM="${DIR_MNT}/customcd/files"
TMP="/tmp/sysresccd-area31"

if [ ! -d ${TMP} ]; then
	mkdir -p ${TMP}
fi

cd /
umount ${DIR_SYSTEM}/usr/portage ${DIR_SYSTEM}/sys ${DIR_SYSTEM}/dev ${DIR_SYSTEM}/proc ${DIR_SYSTEM} &> /dev/null

# gera lista de partições montadas
mount|grep -w ${DIR_SYSTEM}|cut -d" " -f1 > ${TMP}/list-mount &> /dev/null
for disk in $(ls -1 /sys/block/|grep sd[a-z]); do
	mount |grep "/dev/${disk}" |cut -d" " -f1 >> ${TMP}/list-mount &> /dev/null
done

while read device;do
	umount -f ${device} &> /dev/null
done < ${TMP}/list-mount

umount -f ${DIR_MNT}  &> /dev/null
