#!/bin/bash


DIR_MNT="/mnt/custom"
TMP="/tmp/sysresccd-area31"

mkdir -p $TMP

rm -rf $TMP/SeTdevices

# unmounting everything
swapoff -a
/usr/share/sysresccd-area31/sysresccd-area31-umount
sync

fdisk -l 2> /dev/null | egrep -i 'Linux$' | sort 1> $TMP/SeTplist 2> /dev/null

ls -1 /sys/block/|grep sd[a-z] > $TMP/SeTdevices
FILE="$TMP/SeTdevices"

dialog --backtitle "RescueCD Area31 Partition Tools" \
 --title " SELECT A DEVICE " \
 --menu 'Select the device to be PARTITIONED:' \
10 35 6 $(cat $FILE | cut -d: -f1 | sed s,$," # ",) 2> $TMP/selectHD

if [ ! $? = 0 ]; then
	rm $TMP/selectHD
	exit
fi

DEVICE=$( cat $TMP/selectHD )
rm $TMP/selectHD

dialog --backtitle "RescueCD Area31 Partition Tools" \
--title " SELECT A PARTITIONING TOOL " --menu \
"Please select a partitioning tool below to proceed with partitioning:\n" \
11 70 9 \
"CFDISK" "Configure \"${DEVICE}\" device using 'cfdisk' " \
"FDISK" "Configure \"${DEVICE}\" device using 'fdisk'" \
2> $TMP/select
if [ ! $? = 0 ]; then
	rm $TMP/select
	exit
fi

SELECT_CONFIGURE="`cat $TMP/select`"
rm -f $TMP/select
if [ "${SELECT_CONFIGURE}" = "CFDISK" ]; then
	cfdisk /dev/$DEVICE
elif [ "${SELECT_CONFIGURE}" = "FDISK" ]; then
	fdisk /dev/$DEVICE
fi
